In [15]:
#subtracting in matrix
import numpy as np
a=[[4,3],
  [6,9]]
b=[[-2,9],
  [-5,2]]
result=np.absolute(np.array(a)- np.array(b))
print result

[[ 6  6]
 [11  7]]


In [49]:
#multiplication in matrix
import numpy as np

n=np.array([[2],
   [7],
   [4],
   [1]])
m=(1/2)*np.array(n)
mn=n*float(1.0/2)
print mn

[[ 1. ]
 [ 3.5]
 [ 2. ]
 [ 0.5]]


In [51]:
#transpose of a matrix

import numpy as np 
ma=[[8],
    [1],
    [4],[2]]
print np.transpose(ma)
#another example
print 'transpose'
n=[[1,3],
   [2,4],
   [4,5],
   [5,8]]
print np.transpose(n)

[[8 1 4 2]]
transpose
[[1 2 4 5]
 [3 4 5 8]]


In [58]:
#multiplication of matrix with transpose
import numpy as np
a=[[1],
   [3],
   [-1]]
b=[[2],
   [2],
   [4]]

m=np.transpose(a)
print np.matmul(m,b)

[[4]]
